import { storage } from "../storage";
import type { InsertCollege } from "@shared/schema";

const collegeData: InsertCollege[] = [
  // === D1 POWER CONFERENCE - BASKETBALL ===
  {
    name: "Duke University",
    shortName: "Duke",
    city: "Durham",
    state: "NC",
    region: "East",
    division: "D1",
    conference: "ACC",
    academicRating: 98,
    avgGpaRequired: "3.50",
    sport: "basketball",
    programStrength: 98,
    coachingRating: 95,
    facilitiesRating: 99,
    tempoRating: 70,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 2,
  },
  {
    name: "University of Kentucky",
    shortName: "Kentucky",
    city: "Lexington",
    state: "KY",
    region: "South",
    division: "D1",
    conference: "SEC",
    academicRating: 75,
    avgGpaRequired: "2.80",
    sport: "basketball",
    programStrength: 95,
    coachingRating: 90,
    facilitiesRating: 98,
    tempoRating: 85,
    defensiveStyle: "pressure",
    offensiveStyle: "pick_and_roll",
    positionNeeds: JSON.stringify(["Big", "Wing"]),
    scholarshipsAvailable: 3,
  },
  {
    name: "University of Kansas",
    shortName: "Kansas",
    city: "Lawrence",
    state: "KS",
    region: "Midwest",
    division: "D1",
    conference: "Big 12",
    academicRating: 78,
    avgGpaRequired: "2.90",
    sport: "basketball",
    programStrength: 96,
    coachingRating: 94,
    facilitiesRating: 95,
    tempoRating: 65,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 2,
  },
  {
    name: "University of North Carolina",
    shortName: "UNC",
    city: "Chapel Hill",
    state: "NC",
    region: "East",
    division: "D1",
    conference: "ACC",
    academicRating: 88,
    avgGpaRequired: "3.20",
    sport: "basketball",
    programStrength: 94,
    coachingRating: 88,
    facilitiesRating: 96,
    tempoRating: 75,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Wing", "Guard"]),
    scholarshipsAvailable: 1,
  },
  {
    name: "UCLA",
    shortName: "UCLA",
    city: "Los Angeles",
    state: "CA",
    region: "West",
    division: "D1",
    conference: "Big Ten",
    academicRating: 92,
    avgGpaRequired: "3.40",
    sport: "basketball",
    programStrength: 88,
    coachingRating: 85,
    facilitiesRating: 94,
    tempoRating: 70,
    defensiveStyle: "switching",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Big", "Guard"]),
    scholarshipsAvailable: 3,
  },
  {
    name: "Michigan State University",
    shortName: "Michigan St",
    city: "East Lansing",
    state: "MI",
    region: "Midwest",
    division: "D1",
    conference: "Big Ten",
    academicRating: 80,
    avgGpaRequired: "3.00",
    sport: "basketball",
    programStrength: 90,
    coachingRating: 92,
    facilitiesRating: 93,
    tempoRating: 55,
    defensiveStyle: "switching",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 2,
  },
  {
    name: "University of Connecticut",
    shortName: "UConn",
    city: "Storrs",
    state: "CT",
    region: "East",
    division: "D1",
    conference: "Big East",
    academicRating: 82,
    avgGpaRequired: "3.00",
    sport: "basketball",
    programStrength: 92,
    coachingRating: 94,
    facilitiesRating: 90,
    tempoRating: 60,
    defensiveStyle: "man",
    offensiveStyle: "pick_and_roll",
    positionNeeds: JSON.stringify(["Big"]),
    scholarshipsAvailable: 2,
  },
  {
    name: "Gonzaga University",
    shortName: "Gonzaga",
    city: "Spokane",
    state: "WA",
    region: "West",
    division: "D1",
    conference: "WCC",
    academicRating: 85,
    avgGpaRequired: "3.10",
    sport: "basketball",
    programStrength: 93,
    coachingRating: 96,
    facilitiesRating: 88,
    tempoRating: 75,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 3,
  },
  {
    name: "Arizona State University",
    shortName: "Arizona St",
    city: "Tempe",
    state: "AZ",
    region: "West",
    division: "D1",
    conference: "Big 12",
    academicRating: 72,
    avgGpaRequired: "2.70",
    sport: "basketball",
    programStrength: 75,
    coachingRating: 78,
    facilitiesRating: 85,
    tempoRating: 80,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 4,
  },
  {
    name: "University of Houston",
    shortName: "Houston",
    city: "Houston",
    state: "TX",
    region: "South",
    division: "D1",
    conference: "Big 12",
    academicRating: 76,
    avgGpaRequired: "2.80",
    sport: "basketball",
    programStrength: 91,
    coachingRating: 93,
    facilitiesRating: 90,
    tempoRating: 55,
    defensiveStyle: "pressure",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Wing", "Big"]),
    scholarshipsAvailable: 2,
  },

  // === D1 POWER CONFERENCE - FOOTBALL ===
  {
    name: "University of Alabama",
    shortName: "Alabama",
    city: "Tuscaloosa",
    state: "AL",
    region: "South",
    division: "D1",
    conference: "SEC",
    academicRating: 70,
    avgGpaRequired: "2.60",
    sport: "football",
    programStrength: 99,
    coachingRating: 98,
    facilitiesRating: 99,
    tempoRating: 65,
    defensiveStyle: "man",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "LB"]),
    scholarshipsAvailable: 5,
  },
  {
    name: "Ohio State University",
    shortName: "Ohio State",
    city: "Columbus",
    state: "OH",
    region: "Midwest",
    division: "D1",
    conference: "Big Ten",
    academicRating: 80,
    avgGpaRequired: "3.00",
    sport: "football",
    programStrength: 98,
    coachingRating: 95,
    facilitiesRating: 99,
    tempoRating: 75,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["RB", "DB", "OL"]),
    scholarshipsAvailable: 6,
  },
  {
    name: "University of Georgia",
    shortName: "Georgia",
    city: "Athens",
    state: "GA",
    region: "South",
    division: "D1",
    conference: "SEC",
    academicRating: 78,
    avgGpaRequired: "2.90",
    sport: "football",
    programStrength: 97,
    coachingRating: 96,
    facilitiesRating: 98,
    tempoRating: 60,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["WR", "DL", "LB"]),
    scholarshipsAvailable: 4,
  },
  {
    name: "University of Texas",
    shortName: "Texas",
    city: "Austin",
    state: "TX",
    region: "South",
    division: "D1",
    conference: "SEC",
    academicRating: 82,
    avgGpaRequired: "3.10",
    sport: "football",
    programStrength: 92,
    coachingRating: 88,
    facilitiesRating: 98,
    tempoRating: 70,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "DB", "TE"]),
    scholarshipsAvailable: 5,
  },
  {
    name: "University of Michigan",
    shortName: "Michigan",
    city: "Ann Arbor",
    state: "MI",
    region: "Midwest",
    division: "D1",
    conference: "Big Ten",
    academicRating: 90,
    avgGpaRequired: "3.30",
    sport: "football",
    programStrength: 95,
    coachingRating: 92,
    facilitiesRating: 97,
    tempoRating: 50,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["OL", "LB", "WR"]),
    scholarshipsAvailable: 4,
  },
  {
    name: "Clemson University",
    shortName: "Clemson",
    city: "Clemson",
    state: "SC",
    region: "South",
    division: "D1",
    conference: "ACC",
    academicRating: 77,
    avgGpaRequired: "2.85",
    sport: "football",
    programStrength: 91,
    coachingRating: 90,
    facilitiesRating: 96,
    tempoRating: 72,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "RB", "DL"]),
    scholarshipsAvailable: 5,
  },
  {
    name: "University of Southern California",
    shortName: "USC",
    city: "Los Angeles",
    state: "CA",
    region: "West",
    division: "D1",
    conference: "Big Ten",
    academicRating: 88,
    avgGpaRequired: "3.25",
    sport: "football",
    programStrength: 88,
    coachingRating: 87,
    facilitiesRating: 95,
    tempoRating: 80,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["WR", "DB", "OL"]),
    scholarshipsAvailable: 6,
  },
  {
    name: "University of Oregon",
    shortName: "Oregon",
    city: "Eugene",
    state: "OR",
    region: "West",
    division: "D1",
    conference: "Big Ten",
    academicRating: 75,
    avgGpaRequired: "2.80",
    sport: "football",
    programStrength: 90,
    coachingRating: 88,
    facilitiesRating: 99,
    tempoRating: 90,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["RB", "WR", "LB"]),
    scholarshipsAvailable: 5,
  },

  // === D2 SCHOOLS ===
  {
    name: "Colorado School of Mines",
    shortName: "Mines",
    city: "Golden",
    state: "CO",
    region: "West",
    division: "D2",
    conference: "RMAC",
    academicRating: 95,
    avgGpaRequired: "3.60",
    sport: "basketball",
    programStrength: 75,
    coachingRating: 80,
    facilitiesRating: 78,
    tempoRating: 65,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 4,
  },
  {
    name: "Northwest Missouri State",
    shortName: "NW Missouri",
    city: "Maryville",
    state: "MO",
    region: "Midwest",
    division: "D2",
    conference: "MIAA",
    academicRating: 68,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 88,
    coachingRating: 92,
    facilitiesRating: 82,
    tempoRating: 55,
    defensiveStyle: "zone",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["QB", "LB", "OL"]),
    scholarshipsAvailable: 8,
  },
  {
    name: "West Texas A&M",
    shortName: "WT A&M",
    city: "Canyon",
    state: "TX",
    region: "South",
    division: "D2",
    conference: "Lone Star",
    academicRating: 65,
    avgGpaRequired: "2.50",
    sport: "basketball",
    programStrength: 82,
    coachingRating: 85,
    facilitiesRating: 80,
    tempoRating: 85,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 5,
  },
  {
    name: "Ferris State University",
    shortName: "Ferris St",
    city: "Big Rapids",
    state: "MI",
    region: "Midwest",
    division: "D2",
    conference: "GLIAC",
    academicRating: 70,
    avgGpaRequired: "2.60",
    sport: "football",
    programStrength: 85,
    coachingRating: 88,
    facilitiesRating: 78,
    tempoRating: 60,
    defensiveStyle: "man",
    offensiveStyle: "pick_and_roll",
    positionNeeds: JSON.stringify(["RB", "WR", "DB"]),
    scholarshipsAvailable: 7,
  },

  // === D3 SCHOOLS ===
  {
    name: "Williams College",
    shortName: "Williams",
    city: "Williamstown",
    state: "MA",
    region: "East",
    division: "D3",
    conference: "NESCAC",
    academicRating: 99,
    avgGpaRequired: "3.80",
    sport: "basketball",
    programStrength: 78,
    coachingRating: 82,
    facilitiesRating: 85,
    tempoRating: 60,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 0,
  },
  {
    name: "University of Mount Union",
    shortName: "Mount Union",
    city: "Alliance",
    state: "OH",
    region: "Midwest",
    division: "D3",
    conference: "OAC",
    academicRating: 72,
    avgGpaRequired: "2.70",
    sport: "football",
    programStrength: 95,
    coachingRating: 96,
    facilitiesRating: 88,
    tempoRating: 70,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "LB"]),
    scholarshipsAvailable: 0,
  },
  {
    name: "Amherst College",
    shortName: "Amherst",
    city: "Amherst",
    state: "MA",
    region: "East",
    division: "D3",
    conference: "NESCAC",
    academicRating: 99,
    avgGpaRequired: "3.75",
    sport: "basketball",
    programStrength: 72,
    coachingRating: 78,
    facilitiesRating: 82,
    tempoRating: 55,
    defensiveStyle: "zone",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Wing", "Big"]),
    scholarshipsAvailable: 0,
  },
  {
    name: "University of Wisconsin-Whitewater",
    shortName: "UW-Whitewater",
    city: "Whitewater",
    state: "WI",
    region: "Midwest",
    division: "D3",
    conference: "WIAC",
    academicRating: 68,
    avgGpaRequired: "2.60",
    sport: "football",
    programStrength: 90,
    coachingRating: 92,
    facilitiesRating: 80,
    tempoRating: 65,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["RB", "OL", "DL"]),
    scholarshipsAvailable: 0,
  },

  // === NAIA SCHOOLS ===
  {
    name: "Indiana Wesleyan University",
    shortName: "IWU",
    city: "Marion",
    state: "IN",
    region: "Midwest",
    division: "NAIA",
    conference: "Crossroads League",
    academicRating: 75,
    avgGpaRequired: "2.80",
    sport: "basketball",
    programStrength: 85,
    coachingRating: 88,
    facilitiesRating: 78,
    tempoRating: 75,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 6,
  },
  {
    name: "Morningside University",
    shortName: "Morningside",
    city: "Sioux City",
    state: "IA",
    region: "Midwest",
    division: "NAIA",
    conference: "GPAC",
    academicRating: 70,
    avgGpaRequired: "2.60",
    sport: "football",
    programStrength: 92,
    coachingRating: 94,
    facilitiesRating: 82,
    tempoRating: 80,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "DB"]),
    scholarshipsAvailable: 10,
  },
  {
    name: "Lindsey Wilson College",
    shortName: "Lindsey Wilson",
    city: "Columbia",
    state: "KY",
    region: "South",
    division: "NAIA",
    conference: "Mid-South",
    academicRating: 62,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 88,
    coachingRating: 90,
    facilitiesRating: 75,
    tempoRating: 85,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["RB", "LB", "TE"]),
    scholarshipsAvailable: 12,
  },
  {
    name: "Georgetown College (KY)",
    shortName: "Georgetown",
    city: "Georgetown",
    state: "KY",
    region: "South",
    division: "NAIA",
    conference: "Mid-South",
    academicRating: 68,
    avgGpaRequired: "2.60",
    sport: "basketball",
    programStrength: 80,
    coachingRating: 82,
    facilitiesRating: 72,
    tempoRating: 70,
    defensiveStyle: "man",
    offensiveStyle: "pick_and_roll",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 5,
  },

  // === JUCO SCHOOLS ===
  {
    name: "Hutchinson Community College",
    shortName: "Hutch CC",
    city: "Hutchinson",
    state: "KS",
    region: "Midwest",
    division: "JUCO",
    conference: "KJCCC",
    academicRating: 55,
    avgGpaRequired: "2.50",
    sport: "basketball",
    programStrength: 90,
    coachingRating: 88,
    facilitiesRating: 75,
    tempoRating: 85,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 8,
  },
  {
    name: "Iowa Western Community College",
    shortName: "Iowa Western",
    city: "Council Bluffs",
    state: "IA",
    region: "Midwest",
    division: "JUCO",
    conference: "ICCAC",
    academicRating: 52,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 92,
    coachingRating: 90,
    facilitiesRating: 78,
    tempoRating: 75,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "RB", "WR", "DB", "LB"]),
    scholarshipsAvailable: 15,
  },
  {
    name: "Garden City Community College",
    shortName: "Garden City",
    city: "Garden City",
    state: "KS",
    region: "Midwest",
    division: "JUCO",
    conference: "KJCCC",
    academicRating: 50,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 88,
    coachingRating: 85,
    facilitiesRating: 72,
    tempoRating: 80,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["DL", "OL", "WR"]),
    scholarshipsAvailable: 14,
  },
  {
    name: "South Plains College",
    shortName: "South Plains",
    city: "Levelland",
    state: "TX",
    region: "South",
    division: "JUCO",
    conference: "WJCAC",
    academicRating: 52,
    avgGpaRequired: "2.50",
    sport: "basketball",
    programStrength: 85,
    coachingRating: 82,
    facilitiesRating: 70,
    tempoRating: 88,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 6,
  },

  // === ADDITIONAL MID-MAJOR D1 ===
  {
    name: "San Diego State University",
    shortName: "SDSU",
    city: "San Diego",
    state: "CA",
    region: "West",
    division: "D1",
    conference: "Mountain West",
    academicRating: 74,
    avgGpaRequired: "2.90",
    sport: "basketball",
    programStrength: 85,
    coachingRating: 88,
    facilitiesRating: 88,
    tempoRating: 45,
    defensiveStyle: "switching",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 2,
  },
  {
    name: "Boise State University",
    shortName: "Boise St",
    city: "Boise",
    state: "ID",
    region: "West",
    division: "D1",
    conference: "Mountain West",
    academicRating: 70,
    avgGpaRequired: "2.70",
    sport: "football",
    programStrength: 82,
    coachingRating: 85,
    facilitiesRating: 88,
    tempoRating: 70,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "LB"]),
    scholarshipsAvailable: 5,
  },
];

export async function seedColleges(): Promise<void> {
  console.log("Checking if colleges need seeding...");
  
  const existingColleges = await storage.getColleges();
  
  if (existingColleges.length > 0) {
    console.log(`Colleges table already has ${existingColleges.length} entries, skipping seed.`);
    return;
  }
  
  console.log(`Seeding ${collegeData.length} colleges...`);
  
  for (const college of collegeData) {
    await storage.createCollege(college);
  }
  
  console.log(`Successfully seeded ${collegeData.length} colleges.`);
}
