import { db } from "../db";
import { colleges } from "@shared/schema";
import { eq } from "drizzle-orm";
import { storage } from "../storage";

interface RecruitingContact {
  recruitingContactEmail: string;
  recruitingUrl: string;
}

interface LowerDivisionCollege {
  name: string;
  shortName: string;
  city: string;
  state: string;
  region: string;
  division: string;
  conference: string;
  academicRating: number;
  avgGpaRequired: string;
  sport: string;
  programStrength: number;
  coachingRating: number;
  facilitiesRating: number;
  tempoRating: number;
  defensiveStyle: string;
  offensiveStyle: string;
  positionNeeds: string;
  scholarshipsAvailable: number;
  recruitingContactEmail: string;
  recruitingUrl: string;
  winsLastSeason?: number;
  lossesLastSeason?: number;
  conferenceRecord?: string;
  nationalChampionships?: number;
  conferenceChampionships?: number;
  athleteGraduationRate?: number;
  headCoachName?: string;
  headCoachYears?: number;
  draftPicksLast5Years?: number;
  athleticBudget?: string;
  niLOpportunities?: string;
}

const d1RecruitingContacts: Record<string, RecruitingContact> = {
  "Duke University": {
    recruitingContactEmail: "dukebasketball@duke.edu",
    recruitingUrl: "https://goduke.com/sports/mens-basketball/recruiting",
  },
  "University of Kentucky": {
    recruitingContactEmail: "ukbasketball@uky.edu",
    recruitingUrl: "https://ukathletics.com/sports/mbball/recruiting",
  },
  "University of Kansas": {
    recruitingContactEmail: "kuhoops@ku.edu",
    recruitingUrl: "https://kuathletics.com/sports/mbball/recruiting",
  },
  "University of North Carolina": {
    recruitingContactEmail: "uncbasketball@unc.edu",
    recruitingUrl: "https://goheels.com/sports/mbball/recruiting",
  },
  "UCLA": {
    recruitingContactEmail: "uclahoops@athletics.ucla.edu",
    recruitingUrl: "https://uclabruins.com/sports/mens-basketball/recruiting",
  },
  "University of Connecticut": {
    recruitingContactEmail: "uconnhoops@uconn.edu",
    recruitingUrl: "https://uconnhuskies.com/sports/mbball/recruiting",
  },
  "Gonzaga University": {
    recruitingContactEmail: "hoops@gonzaga.edu",
    recruitingUrl: "https://gozags.com/sports/mbball/recruiting",
  },
  "Villanova University": {
    recruitingContactEmail: "basketball@villanova.edu",
    recruitingUrl: "https://villanova.com/sports/mens-basketball/recruiting",
  },
  "University of Michigan": {
    recruitingContactEmail: "umichhoops@umich.edu",
    recruitingUrl: "https://mgoblue.com/sports/mbball/recruiting",
  },
  "Syracuse University": {
    recruitingContactEmail: "orangehoops@syr.edu",
    recruitingUrl: "https://cuse.com/sports/mbball/recruiting",
  },
  "San Diego State University": {
    recruitingContactEmail: "sdsuhoops@sdsu.edu",
    recruitingUrl: "https://goaztecs.com/sports/mens-basketball/recruiting",
  },
  "University of Alabama": {
    recruitingContactEmail: "alabamafb@ua.edu",
    recruitingUrl: "https://rolltide.com/sports/football/recruiting",
  },
  "Ohio State University": {
    recruitingContactEmail: "buckeyesfb@osu.edu",
    recruitingUrl: "https://ohiostatebuckeyes.com/sports/football/recruiting",
  },
  "University of Georgia": {
    recruitingContactEmail: "ugafootball@uga.edu",
    recruitingUrl: "https://georgiadogs.com/sports/football/recruiting",
  },
  "University of Texas": {
    recruitingContactEmail: "texasfootball@austin.utexas.edu",
    recruitingUrl: "https://texassports.com/sports/football/recruiting",
  },
  "Clemson University": {
    recruitingContactEmail: "clemsonfb@clemson.edu",
    recruitingUrl: "https://clemsontigers.com/sports/football/recruiting",
  },
  "University of Michigan Football": {
    recruitingContactEmail: "umichfootball@umich.edu",
    recruitingUrl: "https://mgoblue.com/sports/football/recruiting",
  },
  "Penn State University": {
    recruitingContactEmail: "psurecruiting@psu.edu",
    recruitingUrl: "https://gopsusports.com/sports/football/recruiting",
  },
  "University of Notre Dame": {
    recruitingContactEmail: "irishfootball@nd.edu",
    recruitingUrl: "https://und.com/sports/football/recruiting",
  },
  "University of Oregon": {
    recruitingContactEmail: "ducksfootball@uoregon.edu",
    recruitingUrl: "https://goducks.com/sports/football/recruiting",
  },
  "USC": {
    recruitingContactEmail: "uscfootball@usc.edu",
    recruitingUrl: "https://usctrojans.com/sports/football/recruiting",
  },
  "LSU": {
    recruitingContactEmail: "lsufootball@lsu.edu",
    recruitingUrl: "https://lsusports.net/sports/football/recruiting",
  },
  "Boise State University": {
    recruitingContactEmail: "bsufootball@boisestate.edu",
    recruitingUrl: "https://broncosports.com/sports/football/recruiting",
  },
};

const additionalLowerDivisionColleges: LowerDivisionCollege[] = [
  // === ADDITIONAL D2 BASKETBALL ===
  {
    name: "Bellarmine University",
    shortName: "Bellarmine",
    city: "Louisville",
    state: "KY",
    region: "South",
    division: "D2",
    conference: "ASUN",
    academicRating: 78,
    avgGpaRequired: "3.00",
    sport: "basketball",
    programStrength: 82,
    coachingRating: 85,
    facilitiesRating: 80,
    tempoRating: 65,
    defensiveStyle: "pack_line",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 4,
    recruitingContactEmail: "mbbrecruiting@bellarmine.edu",
    recruitingUrl: "https://bellarmineknights.com/sports/mbball/recruiting",
    winsLastSeason: 22,
    lossesLastSeason: 11,
    conferenceRecord: "10-6",
    nationalChampionships: 3,
    conferenceChampionships: 8,
    athleteGraduationRate: 88,
    headCoachName: "Scotty Davenport",
    headCoachYears: 19,
    draftPicksLast5Years: 0,
    athleticBudget: "$18M",
    niLOpportunities: "Low",
  },
  {
    name: "Nova Southeastern University",
    shortName: "NSU",
    city: "Fort Lauderdale",
    state: "FL",
    region: "South",
    division: "D2",
    conference: "Sunshine State",
    academicRating: 72,
    avgGpaRequired: "2.80",
    sport: "basketball",
    programStrength: 78,
    coachingRating: 80,
    facilitiesRating: 82,
    tempoRating: 70,
    defensiveStyle: "man",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 5,
    recruitingContactEmail: "nsusharks@nova.edu",
    recruitingUrl: "https://nsusharks.com/sports/mbball/recruiting",
    winsLastSeason: 18,
    lossesLastSeason: 12,
    conferenceRecord: "9-7",
    nationalChampionships: 0,
    conferenceChampionships: 2,
    athleteGraduationRate: 82,
    headCoachName: "Jim Crutchfield",
    headCoachYears: 8,
    draftPicksLast5Years: 0,
    athleticBudget: "$12M",
    niLOpportunities: "Low",
  },
  {
    name: "Queens University of Charlotte",
    shortName: "Queens",
    city: "Charlotte",
    state: "NC",
    region: "South",
    division: "D2",
    conference: "ASUN",
    academicRating: 75,
    avgGpaRequired: "2.90",
    sport: "basketball",
    programStrength: 76,
    coachingRating: 78,
    facilitiesRating: 75,
    tempoRating: 68,
    defensiveStyle: "switching",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 4,
    recruitingContactEmail: "queensathletics@queens.edu",
    recruitingUrl: "https://queensathletics.com/sports/mbball/recruiting",
    winsLastSeason: 16,
    lossesLastSeason: 14,
    conferenceRecord: "8-8",
    nationalChampionships: 0,
    conferenceChampionships: 1,
    athleteGraduationRate: 85,
    headCoachName: "Bart Lundy",
    headCoachYears: 5,
    draftPicksLast5Years: 0,
    athleticBudget: "$10M",
    niLOpportunities: "Low",
  },
  // === ADDITIONAL D2 FOOTBALL ===
  {
    name: "Valdosta State University",
    shortName: "Valdosta St",
    city: "Valdosta",
    state: "GA",
    region: "South",
    division: "D2",
    conference: "Gulf South",
    academicRating: 65,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 90,
    coachingRating: 92,
    facilitiesRating: 85,
    tempoRating: 75,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "DB"]),
    scholarshipsAvailable: 10,
    recruitingContactEmail: "vsufootball@valdosta.edu",
    recruitingUrl: "https://vstateblazers.com/sports/football/recruiting",
    winsLastSeason: 11,
    lossesLastSeason: 3,
    conferenceRecord: "7-1",
    nationalChampionships: 4,
    conferenceChampionships: 12,
    athleteGraduationRate: 68,
    headCoachName: "Gary Goff",
    headCoachYears: 6,
    draftPicksLast5Years: 3,
    athleticBudget: "$15M",
    niLOpportunities: "Medium",
  },
  {
    name: "Grand Valley State University",
    shortName: "GVSU",
    city: "Allendale",
    state: "MI",
    region: "Midwest",
    division: "D2",
    conference: "GLIAC",
    academicRating: 72,
    avgGpaRequired: "2.70",
    sport: "football",
    programStrength: 88,
    coachingRating: 90,
    facilitiesRating: 85,
    tempoRating: 70,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["RB", "LB", "OL"]),
    scholarshipsAvailable: 8,
    recruitingContactEmail: "gvsufootball@gvsu.edu",
    recruitingUrl: "https://gvsulakers.com/sports/football/recruiting",
    winsLastSeason: 10,
    lossesLastSeason: 3,
    conferenceRecord: "7-2",
    nationalChampionships: 4,
    conferenceChampionships: 18,
    athleteGraduationRate: 78,
    headCoachName: "Matt Mitchell",
    headCoachYears: 4,
    draftPicksLast5Years: 5,
    athleticBudget: "$20M",
    niLOpportunities: "Medium",
  },
  {
    name: "Pittsburg State University",
    shortName: "Pitt State",
    city: "Pittsburg",
    state: "KS",
    region: "Midwest",
    division: "D2",
    conference: "MIAA",
    academicRating: 68,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 85,
    coachingRating: 88,
    facilitiesRating: 78,
    tempoRating: 65,
    defensiveStyle: "zone",
    offensiveStyle: "pro_style",
    positionNeeds: JSON.stringify(["DL", "TE", "S"]),
    scholarshipsAvailable: 9,
    recruitingContactEmail: "gorillasfb@pittstate.edu",
    recruitingUrl: "https://pittstategorillas.com/sports/football/recruiting",
    winsLastSeason: 9,
    lossesLastSeason: 4,
    conferenceRecord: "6-3",
    nationalChampionships: 0,
    conferenceChampionships: 5,
    athleteGraduationRate: 72,
    headCoachName: "Brian Wright",
    headCoachYears: 8,
    draftPicksLast5Years: 2,
    athleticBudget: "$12M",
    niLOpportunities: "Low",
  },
  // === ADDITIONAL D3 BASKETBALL ===
  {
    name: "Emory University",
    shortName: "Emory",
    city: "Atlanta",
    state: "GA",
    region: "South",
    division: "D3",
    conference: "UAA",
    academicRating: 98,
    avgGpaRequired: "3.70",
    sport: "basketball",
    programStrength: 75,
    coachingRating: 80,
    facilitiesRating: 85,
    tempoRating: 60,
    defensiveStyle: "pack_line",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 0,
    recruitingContactEmail: "emoryhoops@emory.edu",
    recruitingUrl: "https://emoryathletics.com/sports/mbball/recruiting",
    winsLastSeason: 20,
    lossesLastSeason: 8,
    conferenceRecord: "11-3",
    nationalChampionships: 0,
    conferenceChampionships: 4,
    athleteGraduationRate: 96,
    headCoachName: "Jason Zimmerman",
    headCoachYears: 12,
    draftPicksLast5Years: 0,
    athleticBudget: "$8M",
    niLOpportunities: "None",
  },
  {
    name: "Pomona-Pitzer Colleges",
    shortName: "Pomona-Pitzer",
    city: "Claremont",
    state: "CA",
    region: "West",
    division: "D3",
    conference: "SCIAC",
    academicRating: 99,
    avgGpaRequired: "3.80",
    sport: "basketball",
    programStrength: 72,
    coachingRating: 75,
    facilitiesRating: 80,
    tempoRating: 55,
    defensiveStyle: "zone",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 0,
    recruitingContactEmail: "sagehehenshoops@pomona.edu",
    recruitingUrl: "https://sagehehens.com/sports/mbball/recruiting",
    winsLastSeason: 18,
    lossesLastSeason: 9,
    conferenceRecord: "10-4",
    nationalChampionships: 0,
    conferenceChampionships: 3,
    athleteGraduationRate: 98,
    headCoachName: "Charles Katsiaficas",
    headCoachYears: 15,
    draftPicksLast5Years: 0,
    athleticBudget: "$6M",
    niLOpportunities: "None",
  },
  {
    name: "Wheaton College (IL)",
    shortName: "Wheaton",
    city: "Wheaton",
    state: "IL",
    region: "Midwest",
    division: "D3",
    conference: "CCIW",
    academicRating: 90,
    avgGpaRequired: "3.40",
    sport: "basketball",
    programStrength: 78,
    coachingRating: 82,
    facilitiesRating: 78,
    tempoRating: 65,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Wing", "Big"]),
    scholarshipsAvailable: 0,
    recruitingContactEmail: "thunderhoops@wheaton.edu",
    recruitingUrl: "https://athletics.wheaton.edu/sports/mbball/recruiting",
    winsLastSeason: 22,
    lossesLastSeason: 7,
    conferenceRecord: "13-3",
    nationalChampionships: 0,
    conferenceChampionships: 6,
    athleteGraduationRate: 94,
    headCoachName: "Mike Schauer",
    headCoachYears: 10,
    draftPicksLast5Years: 0,
    athleticBudget: "$5M",
    niLOpportunities: "None",
  },
  // === ADDITIONAL D3 FOOTBALL ===
  {
    name: "Mary Hardin-Baylor",
    shortName: "UMHB",
    city: "Belton",
    state: "TX",
    region: "South",
    division: "D3",
    conference: "ASC",
    academicRating: 72,
    avgGpaRequired: "2.70",
    sport: "football",
    programStrength: 95,
    coachingRating: 96,
    facilitiesRating: 88,
    tempoRating: 75,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "DB"]),
    scholarshipsAvailable: 0,
    recruitingContactEmail: "crusadersfb@umhb.edu",
    recruitingUrl: "https://umhbathletics.com/sports/football/recruiting",
    winsLastSeason: 14,
    lossesLastSeason: 1,
    conferenceRecord: "10-0",
    nationalChampionships: 4,
    conferenceChampionships: 15,
    athleteGraduationRate: 78,
    headCoachName: "Pete Fredenburg",
    headCoachYears: 26,
    draftPicksLast5Years: 1,
    athleticBudget: "$8M",
    niLOpportunities: "None",
  },
  {
    name: "North Central College",
    shortName: "North Central",
    city: "Naperville",
    state: "IL",
    region: "Midwest",
    division: "D3",
    conference: "CCIW",
    academicRating: 78,
    avgGpaRequired: "3.00",
    sport: "football",
    programStrength: 92,
    coachingRating: 94,
    facilitiesRating: 82,
    tempoRating: 70,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["RB", "LB", "OL"]),
    scholarshipsAvailable: 0,
    recruitingContactEmail: "cardinalsfb@noctrl.edu",
    recruitingUrl: "https://northcentralcardinals.com/sports/football/recruiting",
    winsLastSeason: 13,
    lossesLastSeason: 2,
    conferenceRecord: "9-0",
    nationalChampionships: 2,
    conferenceChampionships: 8,
    athleteGraduationRate: 85,
    headCoachName: "Jeff Thorne",
    headCoachYears: 11,
    draftPicksLast5Years: 0,
    athleticBudget: "$6M",
    niLOpportunities: "None",
  },
  // === ADDITIONAL NAIA BASKETBALL ===
  {
    name: "Loyola University New Orleans",
    shortName: "Loyola NO",
    city: "New Orleans",
    state: "LA",
    region: "South",
    division: "NAIA",
    conference: "Southern States",
    academicRating: 82,
    avgGpaRequired: "3.00",
    sport: "basketball",
    programStrength: 78,
    coachingRating: 80,
    facilitiesRating: 72,
    tempoRating: 75,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 5,
    recruitingContactEmail: "wolfpackhoops@loyno.edu",
    recruitingUrl: "https://loyolawolfpack.com/sports/mbball/recruiting",
    winsLastSeason: 20,
    lossesLastSeason: 12,
    conferenceRecord: "11-5",
    nationalChampionships: 0,
    conferenceChampionships: 3,
    athleteGraduationRate: 85,
    headCoachName: "Stacy Hollowell",
    headCoachYears: 14,
    draftPicksLast5Years: 0,
    athleticBudget: "$4M",
    niLOpportunities: "Low",
  },
  {
    name: "Life University",
    shortName: "Life",
    city: "Marietta",
    state: "GA",
    region: "South",
    division: "NAIA",
    conference: "Mid-South",
    academicRating: 65,
    avgGpaRequired: "2.50",
    sport: "basketball",
    programStrength: 75,
    coachingRating: 78,
    facilitiesRating: 70,
    tempoRating: 80,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 6,
    recruitingContactEmail: "runningeagles@life.edu",
    recruitingUrl: "https://lifeathletics.com/sports/mbball/recruiting",
    winsLastSeason: 18,
    lossesLastSeason: 14,
    conferenceRecord: "9-7",
    nationalChampionships: 0,
    conferenceChampionships: 1,
    athleteGraduationRate: 72,
    headCoachName: "Eugene Harris",
    headCoachYears: 6,
    draftPicksLast5Years: 0,
    athleticBudget: "$3M",
    niLOpportunities: "Low",
  },
  // === ADDITIONAL NAIA FOOTBALL ===
  {
    name: "Grand View University",
    shortName: "Grand View",
    city: "Des Moines",
    state: "IA",
    region: "Midwest",
    division: "NAIA",
    conference: "Heart of America",
    academicRating: 68,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 90,
    coachingRating: 92,
    facilitiesRating: 78,
    tempoRating: 80,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "WR", "LB"]),
    scholarshipsAvailable: 12,
    recruitingContactEmail: "vikingsfb@grandview.edu",
    recruitingUrl: "https://gvathletics.com/sports/football/recruiting",
    winsLastSeason: 11,
    lossesLastSeason: 2,
    conferenceRecord: "9-0",
    nationalChampionships: 1,
    conferenceChampionships: 8,
    athleteGraduationRate: 70,
    headCoachName: "Joe Woodley",
    headCoachYears: 10,
    draftPicksLast5Years: 2,
    athleticBudget: "$5M",
    niLOpportunities: "Low",
  },
  {
    name: "Keiser University",
    shortName: "Keiser",
    city: "West Palm Beach",
    state: "FL",
    region: "South",
    division: "NAIA",
    conference: "Sun Conference",
    academicRating: 62,
    avgGpaRequired: "2.50",
    sport: "football",
    programStrength: 82,
    coachingRating: 85,
    facilitiesRating: 80,
    tempoRating: 85,
    defensiveStyle: "man",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["RB", "DB", "DL"]),
    scholarshipsAvailable: 15,
    recruitingContactEmail: "seahawksfb@keiseruniversity.edu",
    recruitingUrl: "https://keiserseahawks.com/sports/football/recruiting",
    winsLastSeason: 9,
    lossesLastSeason: 3,
    conferenceRecord: "7-1",
    nationalChampionships: 0,
    conferenceChampionships: 2,
    athleteGraduationRate: 68,
    headCoachName: "Doug Socha",
    headCoachYears: 8,
    draftPicksLast5Years: 1,
    athleticBudget: "$6M",
    niLOpportunities: "Medium",
  },
  // === ADDITIONAL JUCO BASKETBALL ===
  {
    name: "Chipola College",
    shortName: "Chipola",
    city: "Marianna",
    state: "FL",
    region: "South",
    division: "JUCO",
    conference: "Panhandle",
    academicRating: 55,
    avgGpaRequired: "2.00",
    sport: "basketball",
    programStrength: 88,
    coachingRating: 90,
    facilitiesRating: 75,
    tempoRating: 85,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing", "Big"]),
    scholarshipsAvailable: 10,
    recruitingContactEmail: "indianshoops@chipola.edu",
    recruitingUrl: "https://chipolaathletics.com/sports/mbball/recruiting",
    winsLastSeason: 28,
    lossesLastSeason: 5,
    conferenceRecord: "12-2",
    nationalChampionships: 2,
    conferenceChampionships: 15,
    athleteGraduationRate: 55,
    headCoachName: "Donnie Tyndall",
    headCoachYears: 3,
    draftPicksLast5Years: 4,
    athleticBudget: "$2M",
    niLOpportunities: "None",
  },
  {
    name: "Ranger College",
    shortName: "Ranger",
    city: "Ranger",
    state: "TX",
    region: "South",
    division: "JUCO",
    conference: "NTJCAC",
    academicRating: 50,
    avgGpaRequired: "2.00",
    sport: "basketball",
    programStrength: 82,
    coachingRating: 85,
    facilitiesRating: 68,
    tempoRating: 90,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["Guard", "Wing"]),
    scholarshipsAvailable: 8,
    recruitingContactEmail: "rangershoops@rangercollege.edu",
    recruitingUrl: "https://rangerathletics.com/sports/mbball/recruiting",
    winsLastSeason: 24,
    lossesLastSeason: 8,
    conferenceRecord: "10-4",
    nationalChampionships: 0,
    conferenceChampionships: 5,
    athleteGraduationRate: 52,
    headCoachName: "Billy Gillispie",
    headCoachYears: 5,
    draftPicksLast5Years: 2,
    athleticBudget: "$1.5M",
    niLOpportunities: "None",
  },
  {
    name: "Moberly Area CC",
    shortName: "Moberly",
    city: "Moberly",
    state: "MO",
    region: "Midwest",
    division: "JUCO",
    conference: "MCCAC",
    academicRating: 52,
    avgGpaRequired: "2.00",
    sport: "basketball",
    programStrength: 85,
    coachingRating: 88,
    facilitiesRating: 72,
    tempoRating: 80,
    defensiveStyle: "man",
    offensiveStyle: "motion",
    positionNeeds: JSON.stringify(["Guard", "Big"]),
    scholarshipsAvailable: 8,
    recruitingContactEmail: "greyhoundshoops@macc.edu",
    recruitingUrl: "https://maccathletics.com/sports/mbball/recruiting",
    winsLastSeason: 26,
    lossesLastSeason: 6,
    conferenceRecord: "11-3",
    nationalChampionships: 0,
    conferenceChampionships: 8,
    athleteGraduationRate: 58,
    headCoachName: "Patrick Smith",
    headCoachYears: 12,
    draftPicksLast5Years: 3,
    athleticBudget: "$1.8M",
    niLOpportunities: "None",
  },
  // === ADDITIONAL JUCO FOOTBALL ===
  {
    name: "Blinn College",
    shortName: "Blinn",
    city: "Brenham",
    state: "TX",
    region: "South",
    division: "JUCO",
    conference: "SWJCFC",
    academicRating: 52,
    avgGpaRequired: "2.00",
    sport: "football",
    programStrength: 92,
    coachingRating: 94,
    facilitiesRating: 82,
    tempoRating: 80,
    defensiveStyle: "zone",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["QB", "RB", "WR", "LB", "DB"]),
    scholarshipsAvailable: 20,
    recruitingContactEmail: "bucsfb@blinn.edu",
    recruitingUrl: "https://blinnathletics.com/sports/football/recruiting",
    winsLastSeason: 10,
    lossesLastSeason: 2,
    conferenceRecord: "6-1",
    nationalChampionships: 3,
    conferenceChampionships: 12,
    athleteGraduationRate: 48,
    headCoachName: "Ryan Mahon",
    headCoachYears: 6,
    draftPicksLast5Years: 8,
    athleticBudget: "$3M",
    niLOpportunities: "None",
  },
  {
    name: "East Mississippi CC",
    shortName: "EMCC",
    city: "Scooba",
    state: "MS",
    region: "South",
    division: "JUCO",
    conference: "MACCC",
    academicRating: 48,
    avgGpaRequired: "2.00",
    sport: "football",
    programStrength: 95,
    coachingRating: 96,
    facilitiesRating: 75,
    tempoRating: 85,
    defensiveStyle: "pressure",
    offensiveStyle: "spread",
    positionNeeds: JSON.stringify(["DL", "LB", "WR", "OL"]),
    scholarshipsAvailable: 25,
    recruitingContactEmail: "lionsfb@eastms.edu",
    recruitingUrl: "https://emccathletics.com/sports/football/recruiting",
    winsLastSeason: 11,
    lossesLastSeason: 1,
    conferenceRecord: "7-0",
    nationalChampionships: 5,
    conferenceChampionships: 10,
    athleteGraduationRate: 45,
    headCoachName: "Buddy Stephens",
    headCoachYears: 16,
    draftPicksLast5Years: 15,
    athleticBudget: "$2.5M",
    niLOpportunities: "None",
  },
  {
    name: "Independence CC",
    shortName: "ICC",
    city: "Independence",
    state: "KS",
    region: "Midwest",
    division: "JUCO",
    conference: "KJCCC",
    academicRating: 50,
    avgGpaRequired: "2.00",
    sport: "football",
    programStrength: 88,
    coachingRating: 90,
    facilitiesRating: 72,
    tempoRating: 75,
    defensiveStyle: "zone",
    offensiveStyle: "pro_style",
    positionNeeds: JSON.stringify(["QB", "RB", "DB", "OL"]),
    scholarshipsAvailable: 18,
    recruitingContactEmail: "piratesfb@indycc.edu",
    recruitingUrl: "https://indypirates.com/sports/football/recruiting",
    winsLastSeason: 8,
    lossesLastSeason: 3,
    conferenceRecord: "5-2",
    nationalChampionships: 1,
    conferenceChampionships: 6,
    athleteGraduationRate: 50,
    headCoachName: "Jason Brown",
    headCoachYears: 9,
    draftPicksLast5Years: 6,
    athleticBudget: "$1.8M",
    niLOpportunities: "None",
  },
];

const existingD2D3NAIAJUCOContacts: Record<string, RecruitingContact> = {
  "Colorado School of Mines": {
    recruitingContactEmail: "mineshoops@mines.edu",
    recruitingUrl: "https://minesathletics.com/sports/mbball/recruiting",
  },
  "Northwest Missouri State": {
    recruitingContactEmail: "bearfootball@nwmissouri.edu",
    recruitingUrl: "https://bearcatsports.com/sports/football/recruiting",
  },
  "West Texas A&M": {
    recruitingContactEmail: "buffhoops@wtamu.edu",
    recruitingUrl: "https://gobuffsgo.com/sports/mbball/recruiting",
  },
  "Ferris State University": {
    recruitingContactEmail: "bulldogsfb@ferris.edu",
    recruitingUrl: "https://ferrisstatebulldogs.com/sports/football/recruiting",
  },
  "Williams College": {
    recruitingContactEmail: "ephshoops@williams.edu",
    recruitingUrl: "https://ephsports.williams.edu/sports/mbball/recruiting",
  },
  "University of Mount Union": {
    recruitingContactEmail: "raiderfootball@mountunion.edu",
    recruitingUrl: "https://athletics.mountunion.edu/sports/football/recruiting",
  },
  "Amherst College": {
    recruitingContactEmail: "mammoths@amherst.edu",
    recruitingUrl: "https://athletics.amherst.edu/sports/mbball/recruiting",
  },
  "University of Wisconsin-Whitewater": {
    recruitingContactEmail: "warhawksfb@uww.edu",
    recruitingUrl: "https://uwwsports.com/sports/football/recruiting",
  },
  "Indiana Wesleyan University": {
    recruitingContactEmail: "wildcatshoops@indwes.edu",
    recruitingUrl: "https://iwuwildcats.com/sports/mbball/recruiting",
  },
  "Morningside University": {
    recruitingContactEmail: "mustangsfb@morningside.edu",
    recruitingUrl: "https://maborathletics.com/sports/football/recruiting",
  },
  "Lindsey Wilson College": {
    recruitingContactEmail: "blueraiderfb@lindsey.edu",
    recruitingUrl: "https://lindseyathletics.com/sports/football/recruiting",
  },
  "Georgetown College (KY)": {
    recruitingContactEmail: "tigershoops@georgetowncollege.edu",
    recruitingUrl: "https://georgetowncollegeathletics.com/sports/mbball/recruiting",
  },
  "Hutchinson Community College": {
    recruitingContactEmail: "bluedragonshoops@hutchcc.edu",
    recruitingUrl: "https://bluedragonsports.com/sports/mbball/recruiting",
  },
  "Iowa Western Community College": {
    recruitingContactEmail: "reiversfb@iwcc.edu",
    recruitingUrl: "https://reivers.com/sports/football/recruiting",
  },
  "Garden City Community College": {
    recruitingContactEmail: "broncsbusters@gcccks.edu",
    recruitingUrl: "https://gcccsports.com/sports/football/recruiting",
  },
  "South Plains College": {
    recruitingContactEmail: "texanshoops@southplainscollege.edu",
    recruitingUrl: "https://texanathletics.com/sports/mbball/recruiting",
  },
};

export async function seedRecruitingContacts(): Promise<void> {
  console.log("Updating colleges with recruiting contact information...");

  const allContacts = { ...d1RecruitingContacts, ...existingD2D3NAIAJUCOContacts };
  let updatedCount = 0;

  for (const [collegeName, contact] of Object.entries(allContacts)) {
    try {
      await db.update(colleges)
        .set({
          recruitingContactEmail: contact.recruitingContactEmail,
          recruitingUrl: contact.recruitingUrl,
        })
        .where(eq(colleges.name, collegeName));
      
      updatedCount++;
      console.log(`Updated recruiting contacts for ${collegeName}`);
    } catch (error) {
      console.error(`Failed to update ${collegeName}:`, error);
    }
  }

  console.log(`Successfully updated ${updatedCount} colleges with recruiting contacts.`);
}

export async function seedAdditionalLowerDivisionColleges(): Promise<void> {
  console.log("Checking for additional lower division colleges to seed...");

  for (const college of additionalLowerDivisionColleges) {
    try {
      const existing = await db.select().from(colleges).where(eq(colleges.name, college.name));
      
      if (existing.length === 0) {
        await storage.createCollege(college);
        console.log(`Seeded new college: ${college.name}`);
      } else {
        await db.update(colleges)
          .set({
            recruitingContactEmail: college.recruitingContactEmail,
            recruitingUrl: college.recruitingUrl,
            winsLastSeason: college.winsLastSeason,
            lossesLastSeason: college.lossesLastSeason,
            conferenceRecord: college.conferenceRecord,
            nationalChampionships: college.nationalChampionships,
            conferenceChampionships: college.conferenceChampionships,
            athleteGraduationRate: college.athleteGraduationRate,
            headCoachName: college.headCoachName,
            headCoachYears: college.headCoachYears,
            draftPicksLast5Years: college.draftPicksLast5Years,
            athleticBudget: college.athleticBudget,
            niLOpportunities: college.niLOpportunities,
          })
          .where(eq(colleges.name, college.name));
        console.log(`Updated existing college: ${college.name}`);
      }
    } catch (error) {
      console.error(`Failed to seed ${college.name}:`, error);
    }
  }

  console.log("Finished seeding additional lower division colleges.");
}
