import { db } from "../db";
import { colleges } from "@shared/schema";
import { eq } from "drizzle-orm";

interface CollegeStats {
  winsLastSeason: number;
  lossesLastSeason: number;
  conferenceRecord: string;
  nationalChampionships: number;
  conferenceChampionships: number;
  tournamentAppearances: number;
  finalFourAppearances: number;
  nbaPlayersProduced?: number;
  nflPlayersProduced?: number;
  draftPicksLast5Years: number;
  averageMinutesForFreshmen: number;
  athleteGraduationRate: number;
  academicAllAmericans: number;
  athleticBudget: string;
  averageAttendance: number;
  niLOpportunities: string;
  currentRosterSize: number;
  incomingRecruitingClass: number;
  headCoachName: string;
  headCoachYears: number;
  headCoachRecord: string;
}

const basketballStats: Record<string, CollegeStats> = {
  "Duke University": {
    winsLastSeason: 27,
    lossesLastSeason: 9,
    conferenceRecord: "13-7",
    nationalChampionships: 5,
    conferenceChampionships: 21,
    tournamentAppearances: 44,
    finalFourAppearances: 17,
    nbaPlayersProduced: 78,
    draftPicksLast5Years: 12,
    averageMinutesForFreshmen: 24,
    athleteGraduationRate: 92,
    academicAllAmericans: 15,
    athleticBudget: "$130M",
    averageAttendance: 9314,
    niLOpportunities: "High",
    currentRosterSize: 13,
    incomingRecruitingClass: 4,
    headCoachName: "Jon Scheyer",
    headCoachYears: 3,
    headCoachRecord: "78-18",
  },
  "University of Kentucky": {
    winsLastSeason: 23,
    lossesLastSeason: 10,
    conferenceRecord: "12-6",
    nationalChampionships: 8,
    conferenceChampionships: 49,
    tournamentAppearances: 60,
    finalFourAppearances: 17,
    nbaPlayersProduced: 131,
    draftPicksLast5Years: 15,
    averageMinutesForFreshmen: 28,
    athleteGraduationRate: 78,
    academicAllAmericans: 8,
    athleticBudget: "$145M",
    averageAttendance: 20545,
    niLOpportunities: "High",
    currentRosterSize: 14,
    incomingRecruitingClass: 5,
    headCoachName: "Mark Pope",
    headCoachYears: 1,
    headCoachRecord: "23-10",
  },
  "University of Kansas": {
    winsLastSeason: 28,
    lossesLastSeason: 8,
    conferenceRecord: "14-4",
    nationalChampionships: 4,
    conferenceChampionships: 66,
    tournamentAppearances: 51,
    finalFourAppearances: 16,
    nbaPlayersProduced: 86,
    draftPicksLast5Years: 8,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 85,
    academicAllAmericans: 12,
    athleticBudget: "$125M",
    averageAttendance: 16300,
    niLOpportunities: "High",
    currentRosterSize: 13,
    incomingRecruitingClass: 3,
    headCoachName: "Bill Self",
    headCoachYears: 21,
    headCoachRecord: "556-124",
  },
  "University of North Carolina": {
    winsLastSeason: 29,
    lossesLastSeason: 8,
    conferenceRecord: "15-5",
    nationalChampionships: 6,
    conferenceChampionships: 32,
    tournamentAppearances: 53,
    finalFourAppearances: 21,
    nbaPlayersProduced: 115,
    draftPicksLast5Years: 10,
    averageMinutesForFreshmen: 20,
    athleteGraduationRate: 88,
    academicAllAmericans: 18,
    athleticBudget: "$115M",
    averageAttendance: 21750,
    niLOpportunities: "High",
    currentRosterSize: 13,
    incomingRecruitingClass: 4,
    headCoachName: "Hubert Davis",
    headCoachYears: 4,
    headCoachRecord: "92-35",
  },
  "UCLA": {
    winsLastSeason: 24,
    lossesLastSeason: 11,
    conferenceRecord: "12-8",
    nationalChampionships: 11,
    conferenceChampionships: 37,
    tournamentAppearances: 50,
    finalFourAppearances: 19,
    nbaPlayersProduced: 95,
    draftPicksLast5Years: 6,
    averageMinutesForFreshmen: 22,
    athleteGraduationRate: 90,
    academicAllAmericans: 20,
    athleticBudget: "$140M",
    averageAttendance: 11089,
    niLOpportunities: "High",
    currentRosterSize: 14,
    incomingRecruitingClass: 4,
    headCoachName: "Mick Cronin",
    headCoachYears: 6,
    headCoachRecord: "118-64",
  },
  "Michigan State University": {
    winsLastSeason: 20,
    lossesLastSeason: 15,
    conferenceRecord: "9-11",
    nationalChampionships: 2,
    conferenceChampionships: 16,
    tournamentAppearances: 35,
    finalFourAppearances: 10,
    nbaPlayersProduced: 52,
    draftPicksLast5Years: 4,
    averageMinutesForFreshmen: 16,
    athleteGraduationRate: 82,
    academicAllAmericans: 14,
    athleticBudget: "$135M",
    averageAttendance: 14797,
    niLOpportunities: "High",
    currentRosterSize: 14,
    incomingRecruitingClass: 3,
    headCoachName: "Tom Izzo",
    headCoachYears: 29,
    headCoachRecord: "683-277",
  },
  "University of Connecticut": {
    winsLastSeason: 37,
    lossesLastSeason: 3,
    conferenceRecord: "18-2",
    nationalChampionships: 6,
    conferenceChampionships: 12,
    tournamentAppearances: 35,
    finalFourAppearances: 7,
    nbaPlayersProduced: 35,
    draftPicksLast5Years: 8,
    averageMinutesForFreshmen: 15,
    athleteGraduationRate: 84,
    academicAllAmericans: 10,
    athleticBudget: "$95M",
    averageAttendance: 10167,
    niLOpportunities: "Medium",
    currentRosterSize: 13,
    incomingRecruitingClass: 4,
    headCoachName: "Dan Hurley",
    headCoachYears: 7,
    headCoachRecord: "161-69",
  },
  "Gonzaga University": {
    winsLastSeason: 27,
    lossesLastSeason: 8,
    conferenceRecord: "15-1",
    nationalChampionships: 0,
    conferenceChampionships: 25,
    tournamentAppearances: 26,
    finalFourAppearances: 2,
    nbaPlayersProduced: 18,
    draftPicksLast5Years: 7,
    averageMinutesForFreshmen: 20,
    athleteGraduationRate: 95,
    academicAllAmericans: 8,
    athleticBudget: "$42M",
    averageAttendance: 6000,
    niLOpportunities: "Medium",
    currentRosterSize: 14,
    incomingRecruitingClass: 5,
    headCoachName: "Mark Few",
    headCoachYears: 25,
    headCoachRecord: "687-139",
  },
  "Arizona State University": {
    winsLastSeason: 14,
    lossesLastSeason: 18,
    conferenceRecord: "6-12",
    nationalChampionships: 0,
    conferenceChampionships: 4,
    tournamentAppearances: 14,
    finalFourAppearances: 0,
    nbaPlayersProduced: 25,
    draftPicksLast5Years: 2,
    averageMinutesForFreshmen: 26,
    athleteGraduationRate: 76,
    academicAllAmericans: 5,
    athleticBudget: "$125M",
    averageAttendance: 8500,
    niLOpportunities: "Medium",
    currentRosterSize: 15,
    incomingRecruitingClass: 6,
    headCoachName: "Bobby Hurley",
    headCoachYears: 9,
    headCoachRecord: "156-120",
  },
  "University of Houston": {
    winsLastSeason: 32,
    lossesLastSeason: 5,
    conferenceRecord: "15-3",
    nationalChampionships: 0,
    conferenceChampionships: 8,
    tournamentAppearances: 23,
    finalFourAppearances: 6,
    nbaPlayersProduced: 42,
    draftPicksLast5Years: 5,
    averageMinutesForFreshmen: 14,
    athleteGraduationRate: 80,
    academicAllAmericans: 6,
    athleticBudget: "$100M",
    averageAttendance: 7100,
    niLOpportunities: "Medium",
    currentRosterSize: 13,
    incomingRecruitingClass: 3,
    headCoachName: "Kelvin Sampson",
    headCoachYears: 11,
    headCoachRecord: "270-75",
  },
  "Colorado School of Mines": {
    winsLastSeason: 26,
    lossesLastSeason: 6,
    conferenceRecord: "18-4",
    nationalChampionships: 0,
    conferenceChampionships: 5,
    tournamentAppearances: 8,
    finalFourAppearances: 1,
    nbaPlayersProduced: 0,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 12,
    athleteGraduationRate: 98,
    academicAllAmericans: 22,
    athleticBudget: "$12M",
    averageAttendance: 1800,
    niLOpportunities: "Low",
    currentRosterSize: 15,
    incomingRecruitingClass: 4,
    headCoachName: "Pryor Orser",
    headCoachYears: 7,
    headCoachRecord: "142-58",
  },
  "West Texas A&M": {
    winsLastSeason: 28,
    lossesLastSeason: 4,
    conferenceRecord: "18-2",
    nationalChampionships: 1,
    conferenceChampionships: 12,
    tournamentAppearances: 15,
    finalFourAppearances: 4,
    nbaPlayersProduced: 2,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 72,
    academicAllAmericans: 4,
    athleticBudget: "$8M",
    averageAttendance: 2200,
    niLOpportunities: "Low",
    currentRosterSize: 14,
    incomingRecruitingClass: 5,
    headCoachName: "Tom Brown",
    headCoachYears: 12,
    headCoachRecord: "285-86",
  },
  "Williams College": {
    winsLastSeason: 22,
    lossesLastSeason: 6,
    conferenceRecord: "8-2",
    nationalChampionships: 3,
    conferenceChampionships: 14,
    tournamentAppearances: 12,
    finalFourAppearances: 5,
    nbaPlayersProduced: 1,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 14,
    athleteGraduationRate: 99,
    academicAllAmericans: 45,
    athleticBudget: "$5M",
    averageAttendance: 800,
    niLOpportunities: "Low",
    currentRosterSize: 15,
    incomingRecruitingClass: 4,
    headCoachName: "Kevin App",
    headCoachYears: 8,
    headCoachRecord: "168-48",
  },
  "Amherst College": {
    winsLastSeason: 20,
    lossesLastSeason: 8,
    conferenceRecord: "7-3",
    nationalChampionships: 1,
    conferenceChampionships: 8,
    tournamentAppearances: 10,
    finalFourAppearances: 3,
    nbaPlayersProduced: 0,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 12,
    athleteGraduationRate: 99,
    academicAllAmericans: 42,
    athleticBudget: "$4M",
    averageAttendance: 650,
    niLOpportunities: "Low",
    currentRosterSize: 14,
    incomingRecruitingClass: 3,
    headCoachName: "Dave Hixon",
    headCoachYears: 35,
    headCoachRecord: "612-245",
  },
  "Indiana Wesleyan University": {
    winsLastSeason: 30,
    lossesLastSeason: 5,
    conferenceRecord: "15-1",
    nationalChampionships: 4,
    conferenceChampionships: 18,
    tournamentAppearances: 22,
    finalFourAppearances: 8,
    nbaPlayersProduced: 0,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 16,
    athleteGraduationRate: 88,
    academicAllAmericans: 12,
    athleticBudget: "$6M",
    averageAttendance: 1500,
    niLOpportunities: "Low",
    currentRosterSize: 15,
    incomingRecruitingClass: 4,
    headCoachName: "Greg Tonagel",
    headCoachYears: 15,
    headCoachRecord: "385-92",
  },
  "Georgetown College (KY)": {
    winsLastSeason: 22,
    lossesLastSeason: 10,
    conferenceRecord: "12-6",
    nationalChampionships: 0,
    conferenceChampionships: 4,
    tournamentAppearances: 8,
    finalFourAppearances: 1,
    nbaPlayersProduced: 0,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 20,
    athleteGraduationRate: 75,
    academicAllAmericans: 3,
    athleticBudget: "$4M",
    averageAttendance: 800,
    niLOpportunities: "Low",
    currentRosterSize: 14,
    incomingRecruitingClass: 5,
    headCoachName: "Chris Briggs",
    headCoachYears: 6,
    headCoachRecord: "112-68",
  },
  "Hutchinson Community College": {
    winsLastSeason: 32,
    lossesLastSeason: 4,
    conferenceRecord: "18-0",
    nationalChampionships: 2,
    conferenceChampionships: 15,
    tournamentAppearances: 25,
    finalFourAppearances: 8,
    nbaPlayersProduced: 8,
    draftPicksLast5Years: 2,
    averageMinutesForFreshmen: 28,
    athleteGraduationRate: 65,
    academicAllAmericans: 2,
    athleticBudget: "$2M",
    averageAttendance: 1200,
    niLOpportunities: "Low",
    currentRosterSize: 15,
    incomingRecruitingClass: 8,
    headCoachName: "Steve Eck",
    headCoachYears: 18,
    headCoachRecord: "482-112",
  },
  "South Plains College": {
    winsLastSeason: 28,
    lossesLastSeason: 6,
    conferenceRecord: "14-2",
    nationalChampionships: 1,
    conferenceChampionships: 12,
    tournamentAppearances: 18,
    finalFourAppearances: 5,
    nbaPlayersProduced: 5,
    draftPicksLast5Years: 1,
    averageMinutesForFreshmen: 26,
    athleteGraduationRate: 62,
    academicAllAmericans: 1,
    athleticBudget: "$1.5M",
    averageAttendance: 900,
    niLOpportunities: "Low",
    currentRosterSize: 14,
    incomingRecruitingClass: 6,
    headCoachName: "Steve Green",
    headCoachYears: 22,
    headCoachRecord: "548-142",
  },
  "San Diego State University": {
    winsLastSeason: 28,
    lossesLastSeason: 7,
    conferenceRecord: "14-4",
    nationalChampionships: 0,
    conferenceChampionships: 8,
    tournamentAppearances: 14,
    finalFourAppearances: 1,
    nbaPlayersProduced: 12,
    draftPicksLast5Years: 3,
    averageMinutesForFreshmen: 12,
    athleteGraduationRate: 82,
    academicAllAmericans: 8,
    athleticBudget: "$75M",
    averageAttendance: 12414,
    niLOpportunities: "Medium",
    currentRosterSize: 13,
    incomingRecruitingClass: 3,
    headCoachName: "Brian Dutcher",
    headCoachYears: 7,
    headCoachRecord: "168-52",
  },
};

const footballStats: Record<string, CollegeStats> = {
  "University of Alabama": {
    winsLastSeason: 12,
    lossesLastSeason: 2,
    conferenceRecord: "8-0",
    nationalChampionships: 18,
    conferenceChampionships: 31,
    tournamentAppearances: 12,
    finalFourAppearances: 8,
    nflPlayersProduced: 145,
    draftPicksLast5Years: 48,
    averageMinutesForFreshmen: 15,
    athleteGraduationRate: 72,
    academicAllAmericans: 6,
    athleticBudget: "$185M",
    averageAttendance: 101821,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 25,
    headCoachName: "Kalen DeBoer",
    headCoachYears: 1,
    headCoachRecord: "12-2",
  },
  "Ohio State University": {
    winsLastSeason: 11,
    lossesLastSeason: 2,
    conferenceRecord: "8-1",
    nationalChampionships: 8,
    conferenceChampionships: 41,
    tournamentAppearances: 15,
    finalFourAppearances: 6,
    nflPlayersProduced: 168,
    draftPicksLast5Years: 52,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 78,
    academicAllAmericans: 15,
    athleticBudget: "$220M",
    averageAttendance: 104944,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 23,
    headCoachName: "Ryan Day",
    headCoachYears: 5,
    headCoachRecord: "56-8",
  },
  "University of Georgia": {
    winsLastSeason: 14,
    lossesLastSeason: 1,
    conferenceRecord: "8-0",
    nationalChampionships: 3,
    conferenceChampionships: 14,
    tournamentAppearances: 10,
    finalFourAppearances: 5,
    nflPlayersProduced: 125,
    draftPicksLast5Years: 45,
    averageMinutesForFreshmen: 14,
    athleteGraduationRate: 76,
    academicAllAmericans: 8,
    athleticBudget: "$175M",
    averageAttendance: 92746,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 24,
    headCoachName: "Kirby Smart",
    headCoachYears: 8,
    headCoachRecord: "96-15",
  },
  "University of Texas": {
    winsLastSeason: 12,
    lossesLastSeason: 2,
    conferenceRecord: "7-2",
    nationalChampionships: 4,
    conferenceChampionships: 32,
    tournamentAppearances: 12,
    finalFourAppearances: 4,
    nflPlayersProduced: 152,
    draftPicksLast5Years: 28,
    averageMinutesForFreshmen: 16,
    athleteGraduationRate: 80,
    academicAllAmericans: 12,
    athleticBudget: "$220M",
    averageAttendance: 100119,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 22,
    headCoachName: "Steve Sarkisian",
    headCoachYears: 4,
    headCoachRecord: "32-16",
  },
  "University of Michigan": {
    winsLastSeason: 15,
    lossesLastSeason: 0,
    conferenceRecord: "9-0",
    nationalChampionships: 12,
    conferenceChampionships: 45,
    tournamentAppearances: 14,
    finalFourAppearances: 5,
    nflPlayersProduced: 185,
    draftPicksLast5Years: 32,
    averageMinutesForFreshmen: 12,
    athleteGraduationRate: 88,
    academicAllAmericans: 18,
    athleticBudget: "$195M",
    averageAttendance: 110645,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 20,
    headCoachName: "Sherrone Moore",
    headCoachYears: 1,
    headCoachRecord: "8-5",
  },
  "Clemson University": {
    winsLastSeason: 10,
    lossesLastSeason: 4,
    conferenceRecord: "6-2",
    nationalChampionships: 3,
    conferenceChampionships: 8,
    tournamentAppearances: 8,
    finalFourAppearances: 6,
    nflPlayersProduced: 95,
    draftPicksLast5Years: 35,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 82,
    academicAllAmericans: 10,
    athleticBudget: "$145M",
    averageAttendance: 81500,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 23,
    headCoachName: "Dabo Swinney",
    headCoachYears: 16,
    headCoachRecord: "182-38",
  },
  "University of Southern California": {
    winsLastSeason: 8,
    lossesLastSeason: 5,
    conferenceRecord: "5-4",
    nationalChampionships: 11,
    conferenceChampionships: 39,
    tournamentAppearances: 10,
    finalFourAppearances: 4,
    nflPlayersProduced: 215,
    draftPicksLast5Years: 22,
    averageMinutesForFreshmen: 22,
    athleteGraduationRate: 84,
    academicAllAmericans: 14,
    athleticBudget: "$165M",
    averageAttendance: 72000,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 25,
    headCoachName: "Lincoln Riley",
    headCoachYears: 3,
    headCoachRecord: "28-12",
  },
  "University of Oregon": {
    winsLastSeason: 12,
    lossesLastSeason: 2,
    conferenceRecord: "9-0",
    nationalChampionships: 0,
    conferenceChampionships: 5,
    tournamentAppearances: 8,
    finalFourAppearances: 2,
    nflPlayersProduced: 62,
    draftPicksLast5Years: 18,
    averageMinutesForFreshmen: 20,
    athleteGraduationRate: 78,
    academicAllAmericans: 8,
    athleticBudget: "$150M",
    averageAttendance: 54000,
    niLOpportunities: "High",
    currentRosterSize: 85,
    incomingRecruitingClass: 24,
    headCoachName: "Dan Lanning",
    headCoachYears: 3,
    headCoachRecord: "34-7",
  },
  "Northwest Missouri State": {
    winsLastSeason: 13,
    lossesLastSeason: 1,
    conferenceRecord: "11-0",
    nationalChampionships: 6,
    conferenceChampionships: 15,
    tournamentAppearances: 18,
    finalFourAppearances: 10,
    nflPlayersProduced: 12,
    draftPicksLast5Years: 2,
    averageMinutesForFreshmen: 25,
    athleteGraduationRate: 72,
    academicAllAmericans: 8,
    athleticBudget: "$8M",
    averageAttendance: 6500,
    niLOpportunities: "Low",
    currentRosterSize: 100,
    incomingRecruitingClass: 35,
    headCoachName: "Rich Wright",
    headCoachYears: 9,
    headCoachRecord: "98-18",
  },
  "Ferris State University": {
    winsLastSeason: 11,
    lossesLastSeason: 3,
    conferenceRecord: "9-1",
    nationalChampionships: 1,
    conferenceChampionships: 8,
    tournamentAppearances: 12,
    finalFourAppearances: 4,
    nflPlayersProduced: 5,
    draftPicksLast5Years: 1,
    averageMinutesForFreshmen: 22,
    athleteGraduationRate: 75,
    academicAllAmericans: 6,
    athleticBudget: "$6M",
    averageAttendance: 4800,
    niLOpportunities: "Low",
    currentRosterSize: 95,
    incomingRecruitingClass: 30,
    headCoachName: "Tony Annese",
    headCoachYears: 12,
    headCoachRecord: "125-28",
  },
  "University of Mount Union": {
    winsLastSeason: 14,
    lossesLastSeason: 1,
    conferenceRecord: "10-0",
    nationalChampionships: 14,
    conferenceChampionships: 32,
    tournamentAppearances: 28,
    finalFourAppearances: 22,
    nflPlayersProduced: 8,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 85,
    academicAllAmericans: 18,
    athleticBudget: "$4M",
    averageAttendance: 5200,
    niLOpportunities: "Low",
    currentRosterSize: 120,
    incomingRecruitingClass: 40,
    headCoachName: "Geoff Dartt",
    headCoachYears: 8,
    headCoachRecord: "105-12",
  },
  "University of Wisconsin-Whitewater": {
    winsLastSeason: 12,
    lossesLastSeason: 2,
    conferenceRecord: "7-0",
    nationalChampionships: 6,
    conferenceChampionships: 18,
    tournamentAppearances: 22,
    finalFourAppearances: 12,
    nflPlayersProduced: 6,
    draftPicksLast5Years: 1,
    averageMinutesForFreshmen: 20,
    athleteGraduationRate: 80,
    academicAllAmericans: 12,
    athleticBudget: "$3M",
    averageAttendance: 4000,
    niLOpportunities: "Low",
    currentRosterSize: 110,
    incomingRecruitingClass: 38,
    headCoachName: "Kevin Bullis",
    headCoachYears: 10,
    headCoachRecord: "98-22",
  },
  "Morningside University": {
    winsLastSeason: 14,
    lossesLastSeason: 1,
    conferenceRecord: "11-0",
    nationalChampionships: 4,
    conferenceChampionships: 12,
    tournamentAppearances: 15,
    finalFourAppearances: 8,
    nflPlayersProduced: 4,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 28,
    athleteGraduationRate: 74,
    academicAllAmericans: 5,
    athleticBudget: "$5M",
    averageAttendance: 3200,
    niLOpportunities: "Low",
    currentRosterSize: 90,
    incomingRecruitingClass: 32,
    headCoachName: "Steve Ryan",
    headCoachYears: 25,
    headCoachRecord: "285-42",
  },
  "Lindsey Wilson College": {
    winsLastSeason: 11,
    lossesLastSeason: 2,
    conferenceRecord: "8-1",
    nationalChampionships: 0,
    conferenceChampionships: 6,
    tournamentAppearances: 10,
    finalFourAppearances: 3,
    nflPlayersProduced: 2,
    draftPicksLast5Years: 0,
    averageMinutesForFreshmen: 30,
    athleteGraduationRate: 68,
    academicAllAmericans: 2,
    athleticBudget: "$4M",
    averageAttendance: 2500,
    niLOpportunities: "Low",
    currentRosterSize: 85,
    incomingRecruitingClass: 35,
    headCoachName: "Chris Oliver",
    headCoachYears: 8,
    headCoachRecord: "82-18",
  },
  "Iowa Western Community College": {
    winsLastSeason: 10,
    lossesLastSeason: 2,
    conferenceRecord: "6-0",
    nationalChampionships: 1,
    conferenceChampionships: 8,
    tournamentAppearances: 12,
    finalFourAppearances: 4,
    nflPlayersProduced: 45,
    draftPicksLast5Years: 8,
    averageMinutesForFreshmen: 35,
    athleteGraduationRate: 58,
    academicAllAmericans: 1,
    athleticBudget: "$2M",
    averageAttendance: 2200,
    niLOpportunities: "Low",
    currentRosterSize: 85,
    incomingRecruitingClass: 45,
    headCoachName: "Scott Strohmeier",
    headCoachYears: 14,
    headCoachRecord: "142-28",
  },
  "Garden City Community College": {
    winsLastSeason: 9,
    lossesLastSeason: 3,
    conferenceRecord: "5-1",
    nationalChampionships: 0,
    conferenceChampionships: 5,
    tournamentAppearances: 8,
    finalFourAppearances: 2,
    nflPlayersProduced: 28,
    draftPicksLast5Years: 5,
    averageMinutesForFreshmen: 32,
    athleteGraduationRate: 55,
    academicAllAmericans: 0,
    athleticBudget: "$1.5M",
    averageAttendance: 1800,
    niLOpportunities: "Low",
    currentRosterSize: 80,
    incomingRecruitingClass: 42,
    headCoachName: "Jeff Sims",
    headCoachYears: 18,
    headCoachRecord: "165-52",
  },
  "Boise State University": {
    winsLastSeason: 12,
    lossesLastSeason: 2,
    conferenceRecord: "8-0",
    nationalChampionships: 0,
    conferenceChampionships: 12,
    tournamentAppearances: 8,
    finalFourAppearances: 1,
    nflPlayersProduced: 48,
    draftPicksLast5Years: 12,
    averageMinutesForFreshmen: 18,
    athleteGraduationRate: 76,
    academicAllAmericans: 10,
    athleticBudget: "$65M",
    averageAttendance: 36387,
    niLOpportunities: "Medium",
    currentRosterSize: 85,
    incomingRecruitingClass: 22,
    headCoachName: "Spencer Danielson",
    headCoachYears: 1,
    headCoachRecord: "12-2",
  },
};

export async function updateCollegeStats(): Promise<void> {
  console.log("Updating colleges with real program statistics...");

  const allStats = { ...basketballStats, ...footballStats };
  let updatedCount = 0;

  for (const [collegeName, stats] of Object.entries(allStats)) {
    try {
      const result = await db.update(colleges)
        .set({
          winsLastSeason: stats.winsLastSeason,
          lossesLastSeason: stats.lossesLastSeason,
          conferenceRecord: stats.conferenceRecord,
          nationalChampionships: stats.nationalChampionships,
          conferenceChampionships: stats.conferenceChampionships,
          tournamentAppearances: stats.tournamentAppearances,
          finalFourAppearances: stats.finalFourAppearances,
          nbaPlayersProduced: stats.nbaPlayersProduced ?? 0,
          nflPlayersProduced: stats.nflPlayersProduced ?? 0,
          draftPicksLast5Years: stats.draftPicksLast5Years,
          averageMinutesForFreshmen: stats.averageMinutesForFreshmen,
          athleteGraduationRate: stats.athleteGraduationRate,
          academicAllAmericans: stats.academicAllAmericans,
          athleticBudget: stats.athleticBudget,
          averageAttendance: stats.averageAttendance,
          niLOpportunities: stats.niLOpportunities,
          currentRosterSize: stats.currentRosterSize,
          incomingRecruitingClass: stats.incomingRecruitingClass,
          headCoachName: stats.headCoachName,
          headCoachYears: stats.headCoachYears,
          headCoachRecord: stats.headCoachRecord,
        })
        .where(eq(colleges.name, collegeName));
      
      updatedCount++;
      console.log(`Updated ${collegeName}`);
    } catch (error) {
      console.error(`Failed to update ${collegeName}:`, error);
    }
  }

  console.log(`Successfully updated ${updatedCount} colleges with statistics.`);
}
